### ISSUE TITLE
AttributeError: 'GlobalStorage' object has no attribute 'u' 

### ISSUE THREAD

**Issue by josyulakrishna** [tomdbar/ecord#4]
Hi, I'm trying to run the code locally without docker, I'm getting the error which says "_AttributeError: 'GlobalStorage' object has no attribute 'u'_ "

` $ python experiments/train.py --save_loc data/training/ --name run1`

``` GPU found! Creating solver on device 'cuda' with output on 'cuda'.
Saving NetworkConfig to data/training/run1/info/network.config...done.
Traceback (most recent call last):
  File "/home/josyula/miniconda3/lib/python3.9/site-packages/torch_geometric/data/storage.py", line 50, in __getattr__
    return self[key]
  File "/home/josyula/miniconda3/lib/python3.9/site-packages/torch_geometric/data/storage.py", line 70, in __getitem__
    return self._mapping[key]
KeyError: 'u'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/josyula/Programs/ecord/experiments/train.py", line 265, in <module>
    trainer.train(
  File "/home/josyula/Programs/ecord/ecord/train/trainer.py", line 279, in train
    log = self.solver.rollout(
  File "/home/josyula/miniconda3/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/josyula/Programs/ecord/ecord/solvers/solver.py", line 252, in rollout
    self.actor.initialise_embeddings(batch, num_tradj)
  File "/home/josyula/Programs/ecord/ecord/solvers/actors/_base.py", line 207, in initialise_embeddings
    u=batch.tg.u,
  File "/home/josyula/miniconda3/lib/python3.9/site-packages/torch_geometric/data/data.py", line 362, in __getattr__
    return getattr(self._store, key)
  File "/home/josyula/miniconda3/lib/python3.9/site-packages/torch_geometric/data/storage.py", line 52, in __getattr__
    raise AttributeError(
AttributeError: 'GlobalStorage' object has no attribute 'u'
 ```

I've not been able to figure out a way to fix this, can you please help? thank you

**Comment by tomdbar** [comment]
Hello.  I can't reproduce this error when building the Docker from scratch - however, I think the above error is related to having the wrong version of torch_geometric installed.  If you build a fresh Docker image does the problem persist?

**Comment by josyulakrishna** [comment]
Thank you for the response @tomdbar issue doesn't occur on a Docker image, I will close this issue.
